name: Exécuter les tests PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configuration de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Spécifiez la version de PHP appropriée

      - name: Installation des dépendances
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Exécution des tests PHPUnit
        run: vendor/bin/phpunit --coverage-text
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
